// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the event log says happened. Creation is absent by design: it is
 * already attributed on the object itself (DECISIONS 0024).
 */
export type ActionTag = "edited" | "deleted";
