// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the item is found in the shop. Declaration order is the walking
 * order the cart sorts by — that ordering lives in `domain`, and this is
 * only its name on the wire.
 */
export type AisleTag = "produce" | "butcher" | "fish" | "deli" | "dairy" | "bakery" | "grocery" | "frozen" | "beverages" | "household" | "other";
