// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CartLineView } from "./CartLineView";

/**
 * The shop screen. Three sections, because "bought" and "already at home"
 * are not the same statement and merging them makes unchecking a staple
 * hard to discover (DECISIONS 0023).
 */
export type CartView = { to_buy: Array<CartLineView>, bought: Array<CartLineView>, at_home: Array<CartLineView>, 
/**
 * Lines still to pick up, and lines in total — the "12 / 20" a person
 * glances at while walking.
 */
remaining: number, total: number, };
