// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AisleTag } from "./AisleTag";
import type { CheckStateTag } from "./CheckStateTag";
import type { QuantityView } from "./QuantityView";

export type CartLineView = { ingredient: string, name: string, aisle: AisleTag, staple: boolean, 
/**
 * Usually one. More than one when the contributions could not be merged
 * — "300 g + 2 tbsp" is the honest rendering when no density is known
 * (Rule 5).
 */
amounts: Array<QuantityView>, state: CheckStateTag, 
/**
 * Who ticked it, when it is known. A name, not an id: attribution is a
 * label (Rule 7).
 */
checked_by: string | null, checked_at: number | null, 
/**
 * Which list entries asked for this. One tap advances every one of them.
 */
sources: Array<string>, };
