// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AisleTag } from "./AisleTag";
import type { CheckStateTag } from "./CheckStateTag";
import type { KeepingTag } from "./KeepingTag";
import type { QuantityView } from "./QuantityView";

export type CartLineView = { ingredient: string, name: string, aisle: AisleTag, 
/**
 * The trips this line appears on — **already resolved** (DECISIONS
 * 0071).
 *
 * Not a copy of the ingredient's own list: an ingredient nobody has
 * placed, and one whose named shops have all been forgotten since, both
 * arrive here naming *every* shop, because hiding such a line from the
 * screen that would have prompted somebody to place it is how it stops
 * being bought. `domain::sold_at` decides that, so the frontend filters
 * by plain membership and holds no rule (Rule 9).
 *
 * The ingredient's own answer — what the form edits — is
 * [`IngredientView::shops`].
 */
shops: Array<string>, 
/**
 * Where it goes once it is home (DECISIONS 0070). On the cart line
 * because that is the row still on screen when the bags are being
 * emptied.
 */
keeping: KeepingTag, staple: boolean, 
/**
 * Usually one. More than one when the contributions could not be merged
 * — "300 g + 2 tbsp" is the honest rendering when no density is known
 * (Rule 5).
 */
amounts: Array<QuantityView>, state: CheckStateTag, 
/**
 * Who ticked it, when it is known. A name, not an id: attribution is a
 * label (Rule 7).
 */
checked_by: string | null, checked_at: number | null, 
/**
 * The ingredient's photo, if it has one — an id, never bytes. The
 * frontend asks the core for those separately and may not get them yet
 * (DECISIONS 0062). This is the line where recognising a product in an
 * aisle actually happens.
 */
photo: string | null, 
/**
 * Which list entries asked for this. One tap advances every one of them.
 */
sources: Array<string>, };
