// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a cart line shows. `Checked` and `AutoChecked` are both settled but
 * they do not mean the same thing, and the UI keeps them in two separate
 * sections for that reason (DECISIONS 0023).
 */
export type CheckStateTag = "to_buy" | "checked" | "auto_checked";
