// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IngredientInput } from "./IngredientInput";
import type { QuantityInput } from "./QuantityInput";
import type { RecipeInput } from "./RecipeInput";

export type Command = { "command": "save_ingredient", ingredient: IngredientInput, } | { "command": "delete_ingredient", ingredient: string, } | { "command": "save_recipe", recipe: RecipeInput, } | { "command": "delete_recipe", recipe: string, } | { "command": "add_recipe_to_list", recipe: string, servings: number, } | { "command": "add_ingredient_to_list", ingredient: string, quantity: QuantityInput, } | { "command": "set_entry_servings", entry: string, servings: number, } | { "command": "remove_list_entry", entry: string, } | { "command": "toggle_cart_item", ingredient: string, } | { "command": "finish_shopping" } | { "command": "open_recipe", recipe: string, servings: number | null, } | { "command": "close_recipe" } | { "command": "rename_user", name: string, };
