// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuantityView } from "./QuantityView";
import type { SubRecipeAmountView } from "./SubRecipeAmountView";

export type ComponentView = { "kind": "ingredient", usage: string, ingredient: string, 
/**
 * The library name, or `None` if the ingredient is gone — the line
 * still renders, with a warning (DECISIONS 0022).
 */
name: string | null, quantity: QuantityView, } | { "kind": "sub_recipe", usage: string, recipe: string, name: string | null, amount: SubRecipeAmountView, };
