// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuantityInput } from "./QuantityInput";
import type { SubRecipeAmountInput } from "./SubRecipeAmountInput";

/**
 * One line of a recipe's ingredient list.
 */
export type ComponentInput = { "kind": "ingredient", 
/**
 * The *usage* id — absent on a new line. Steps reference this, not
 * the ingredient, so that a recipe using flour twice can render the
 * right amount in each step (DECISIONS 0022).
 */
id: string | null, ingredient: string, quantity: QuantityInput, } | { "kind": "sub_recipe", id: string | null, recipe: string, amount: SubRecipeAmountInput, };
