// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeviceView = { id: string, name: string, 
/**
 * The device this state was rendered on.
 */
is_this_one: boolean, 
/**
 * When it joined the family, in milliseconds since the epoch.
 *
 * A number rather than text: a millisecond count is nowhere near where a
 * double stops being exact (DECISIONS 0046), and the words around a date
 * belong to the frontend (0035) — "il y a deux mois" is a sentence, and
 * this crate writes none.
 */
paired_at: number, };
