// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionTag } from "./ActionTag";
import type { SubjectTag } from "./SubjectTag";

/**
 * One line of the event log: what the data itself cannot remember.
 *
 * Deletions and edits leave no field behind to hold "and Alexis did this",
 * so they are recorded (DECISIONS 0024). A courtesy, capped, and never an
 * audit trail — with one shared key any device can write any of these under
 * any name (Rule 7).
 */
export type EventView = { 
/**
 * Milliseconds since the epoch, from *the clock of the device that did
 * it*. Two devices' clocks disagree, so this is worth showing as "two
 * days ago" and not worth sorting a timeline by — which is why the log
 * arrives in merge order and stays that way.
 */
at: number, 
/**
 * The name of whoever did it, or `None` if that person is no longer in
 * the document. The frontend has a word for that case; this crate does
 * not write one (DECISIONS 0035).
 */
by: string | null, 
/**
 * Whether that was this device's own person.
 */
by_me: boolean, action: ActionTag, subject: SubjectTag, 
/**
 * What the thing was called **when it happened** — copied at the time,
 * because the entries that matter most are the ones whose subject no
 * longer exists to be looked up.
 */
label: string, };
