// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecipeInput } from "./RecipeInput";
import type { RecipeView } from "./RecipeView";

/**
 * The open recipe: what to read, and what to edit.
 *
 * Both, because they are not the same shape. `recipe` is rendered at the
 * current servings — quantities scaled, step references resolved. `edit` is
 * the recipe as written, in exactly the form [`crate::Command::SaveRecipe`]
 * takes, so the editor is a form the frontend fills and hands back rather
 * than a structure it has to rebuild from rendered text.
 */
export type FocusView = { recipe: RecipeView, edit: RecipeInput, };
