// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who this device says it is.
 *
 * **Supplied by the host, never invented here.** The ids have to survive a
 * restart or every launch would look like a new person to the rest of the
 * family, and where a device remembers things about *itself* is a host
 * concern: `localStorage` in the PWA, a config file under Tauri. The family
 * document holds the [`cabas_domain::User`] and [`cabas_domain::Device`]
 * records these ids point at — that half *is* shared, and [`crate::App`]
 * writes it on first open.
 *
 * Plain strings rather than domain id types because this crosses the JS
 * boundary verbatim: the host stores what it is given and hands it back.
 *
 * Attribution built on this is declarative, never access control (Rule 7).
 */
export type Identity = { user: string, user_name: string, device: string, device_name: string, };
