// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportReport } from "./ImportReport";
import type { StateView } from "./StateView";

/**
 * What an import hands back: the receipt, and the state it produced.
 *
 * The state comes with it for the reason every mutation returns one
 * (DECISIONS 0033) — an import changes more of the screen than anything else
 * the app does, and asking for it separately would be a second crossing of
 * the boundary and a window in which the two disagree.
 */
export type Imported = { report: ImportReport, state: StateView, };
