// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one import did.
 *
 * Shown, not logged. An import writes as much as a month of ordinary use and
 * the event log is capped at 200 entries (`EventLog::CAP`), so recording it
 * there would push out the deletions the log exists for — and "imported"
 * has no subject to be recorded against without widening the persisted
 * `subject_kind`, which `save_shop` already declined to buy for a row nobody
 * reads. This is the receipt instead, handed straight back to the screen
 * that asked.
 */
export type ImportReport = { shops_added: number, shops_updated: number, ingredients_added: number, ingredients_updated: number, recipes_added: number, recipes_updated: number, 
/**
 * Photos stored. Counted by the host, which is what awaits the store.
 */
photos_added: number, 
/**
 * Recipes that arrived naming an ingredient or a sub-recipe this library
 * does not have — because the file was trimmed to one recipe, or written
 * by hand with a name nothing answers to.
 *
 * Not a failure. The reference is kept and renders as a warning, which
 * is the defined rendering for a reference that points at nothing
 * (DECISIONS 0034); naming the recipes here is what turns "there is a
 * warning somewhere" into a place to look.
 */
incomplete: Array<string>, };
