// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AisleTag } from "./AisleTag";

export type IngredientView = { id: string, name: string, aliases: Array<string>, aisle: AisleTag, staple: boolean, density: string | null, unit_weight: string | null, };
