// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AisleTag } from "./AisleTag";
import type { QuantityInput } from "./QuantityInput";

export type IngredientView = { id: string, name: string, aliases: Array<string>, aisle: AisleTag, staple: boolean, density: string | null, unit_weight: string | null, 
/**
 * How much of it one usually buys, if anybody said (DECISIONS 0066).
 *
 * Shaped like the input the form writes back and the command that adds
 * it to a list takes, rather than like a rendered `QuantityView`: this
 * is the value an edit form has to put in its fields, and a form must
 * render losslessly or it writes a rounded amount back on the next save.
 * `FocusView::edit` carries a `RecipeInput` for the same reason.
 *
 * `None` is "nobody said", which is not the same as one piece — the
 * form shows an empty field, and the core substitutes a piece at the
 * moment it is needed.
 */
default_quantity: QuantityInput | null, 
/**
 * The ingredient's photo, if it has one. An id; see
 * `CartLineView::photo`.
 */
photo: string | null, };
