// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AisleTag } from "./AisleTag";

export type IngredientInput = { 
/**
 * Absent on creation. Present — and unchanged — on every edit.
 */
id: string | null, name: string, aliases: Array<string>, aisle: AisleTag, staple: boolean, 
/**
 * Grams per millilitre, as text. What makes mass ↔ volume possible for
 * this ingredient; absent, the cart keeps the two on separate lines
 * rather than guessing (Rule 5).
 */
density: string | null, 
/**
 * Grams per piece, as text. Same bargain, for count ↔ mass.
 */
unit_weight: string | null, };
