// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AisleTag } from "./AisleTag";
import type { KeepingTag } from "./KeepingTag";
import type { QuantityInput } from "./QuantityInput";

export type IngredientInput = { 
/**
 * Absent on creation. Present — and unchanged — on every edit.
 */
id: string | null, name: string, aliases: Array<string>, aisle: AisleTag, 
/**
 * The ids of the shops this can be bought at, in the order they are to
 * be read (DECISIONS 0071). Ids and never names: a shop is created by
 * [`Command::SaveShop`] before it is referred to here, so that "Biocoop"
 * typed twice is one shop and not two.
 *
 * Empty means "nobody has said", which the cart reads as every shop.
 */
shops: Array<string>, 
/**
 * Fridge, freezer or neither (DECISIONS 0070). Defaulted rather than
 * optional: every ingredient is kept somewhere, and "a cupboard" is the
 * honest answer for one nobody has thought about.
 */
keeping: KeepingTag, staple: boolean, 
/**
 * Grams per millilitre, as text. What makes mass ↔ volume possible for
 * this ingredient; absent, the cart keeps the two on separate lines
 * rather than guessing (Rule 5).
 */
density: string | null, 
/**
 * Grams per piece, as text. Same bargain, for count ↔ mass.
 */
unit_weight: string | null, 
/**
 * How much of this one buys when nobody says how much — a kilo of
 * flour, six eggs (DECISIONS 0066). Absent means one piece, decided by
 * [`cabas_domain::Ingredient::shopping_quantity`] rather than here.
 *
 * A shopping quantity and not a cooking one: no recipe reads it.
 */
default_quantity: QuantityInput | null, 
/**
 * The id of a photo already stored by [`crate::photos::Photos::put`],
 * or `null` to detach the one that is there.
 *
 * An id and never bytes: attaching a photo is this ordinary save, while
 * the bytes went to a store of their own on a call that could be awaited
 * (DECISIONS 0062). Sending it whole on every save is what makes an edit
 * that does not mention the photo keep it.
 */
photo: string | null, };
