// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a thing is kept once it is home (DECISIONS 0070). Not a shopping
 * attribute: it is read while the bags are emptied, not while they are
 * filled.
 */
export type KeepingTag = "ambient" | "fridge" | "freezer";
