// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ListItemView } from "./ListItemView";
import type { ProgressView } from "./ProgressView";

export type ListEntryView = { id: string, item: ListItemView, progress: ProgressView, added_by: string | null, 
/**
 * Milliseconds since the Unix epoch. The frontend renders "il y a 2 h" —
 * relative time is presentation, and the clock it is relative to is the
 * reader's.
 */
added_at: number, };
