// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuantityView } from "./QuantityView";

export type ListItemView = { "kind": "recipe", recipe: string, name: string, 
/**
 * What this entry is cooked for.
 */
servings: number, 
/**
 * What the recipe itself is written for, so the UI can show that the
 * two differ.
 */
written_for: number, } | { "kind": "ingredient", ingredient: string, name: string, quantity: QuantityView, };
