// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceView } from "./DeviceView";

/**
 * One person in the family, and the devices they carry.
 *
 * **Names, not permissions** (Rule 7, DECISIONS 0024). One shared key
 * decrypts the whole document, so every one of these says who most likely
 * did something — not who was allowed to. The screen that lists them is the
 * one place the UI is required to say so out loud, because it is the screen
 * that looks most like an access control panel and is not one.
 */
export type PersonView = { id: string, name: string, 
/**
 * The person this device belongs to.
 */
is_me: boolean, devices: Array<DeviceView>, };
