// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One photo message, after this device's store has been brought up to date
 * with it.
 *
 * Tagged the way [`crate::SyncEvent`] is, because the same kind of host
 * switches on it: the tag is `event`, the variants are `snake_case`.
 */
export type PhotoEvent = { "event": "reconciled", upload: number, download: number, } | { "event": "received", id: string, } | { "event": "sent", id: string, } | { "event": "absent", id: string, } | { "event": "rejected", id: string, reason: string, } | { "event": "dropped", id: string, } | { "event": "refused", reason: string, };
