// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where one photo connection has got to.
 *
 * Nothing here is persisted, which is the whole difference from
 * [`crate::SyncStatus`]: a photo transfer has no cursor to remember, because
 * the next hello re-derives the work from what is actually on disk at both
 * ends (DECISIONS 0080). It is read to draw progress and to decide when to
 * close the socket.
 */
export type PhotoStatus = { 
/**
 * Photos still to move: queued, plus sent and not yet answered.
 */
pending: number, 
/**
 * Photos written to this device's store on this connection.
 */
received: number, 
/**
 * Photos the relay confirmed durable on this connection.
 */
sent: number, 
/**
 * Photos that arrived and were not stored, for any of the three reasons
 * [`PhotoEvent::Dropped`] names.
 */
dropped: number, 
/**
 * The queues have drained and every message is answered — close the
 * socket.
 */
done: boolean, };
