// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProblemKind } from "./ProblemKind";

/**
 * Something the data says that cannot be honoured.
 *
 * Always the shape of a concurrent edit: one device deleted a recipe the
 * other still had on its list, or a sub-recipe chain became a cycle when two
 * halves of it merged. The entry stays visible and the rest of the cart
 * still derives — an empty screen would be the worst possible response to
 * one broken row.
 */
export type ProblemView = { 
/**
 * The list entry that could not be used, when the problem has one.
 */
entry: string | null, 
/**
 * What is missing or broken — a recipe or an ingredient id — so the UI
 * can mark the row it belongs to rather than only the list.
 */
subject: string | null, kind: ProblemKind, 
/**
 * The domain's own message. English, and a diagnostic rather than UI
 * copy: the frontend shows its own sentence per `kind` and keeps this
 * for the details view.
 */
detail: string, };
