// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProblemKind = "missing_recipe" | "missing_ingredient" | "broken_graph" | "broken_yield";
