// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How far through an entry the shopping has got — "5 / 7" against a recipe
 * until every ingredient it contributed is settled (DECISIONS 0020).
 */
export type ProgressView = { settled: number, total: number, complete: boolean, };
