// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnitTag } from "./UnitTag";

/**
 * An amount, ready to display.
 *
 * `amount` is text and never a number: the value behind it is an exact
 * rational, and any numeric type the frontend could hold it in would be a
 * float (Rule 4).
 */
export type QuantityView = { amount: string, unit: UnitTag, 
/**
 * The rendering is rounded — 28.35 g where the exact value is
 * 28.349523125. The UI may show a "≈"; the cart still adds up the exact
 * value underneath.
 */
approximate: boolean, };
