// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnitTag } from "./UnitTag";

/**
 * A quantity as typed: `{ amount: "1,5", unit: "kg" }`.
 */
export type QuantityInput = { amount: string, unit: UnitTag, };
