// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentInput } from "./ComponentInput";
import type { QuantityInput } from "./QuantityInput";
import type { StepInput } from "./StepInput";

export type RecipeInput = { id: string | null, name: string, 
/**
 * How many people the quantities as written serve. Must be at least one.
 */
servings: number, 
/**
 * What it produces — "makes 500 g". Required before another recipe can
 * take an amount *of* it (DECISIONS 0017).
 */
yields: QuantityInput | null, components: Array<ComponentInput>, steps: Array<StepInput>, };
