// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuantityView } from "./QuantityView";

export type RecipeSummaryView = { id: string, name: string, servings: number, yields: QuantityView | null, ingredients: number, sub_recipes: number, };
