// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentView } from "./ComponentView";
import type { QuantityView } from "./QuantityView";
import type { StepView } from "./StepView";

export type RecipeView = { id: string, name: string, 
/**
 * What the recipe is written for, and what it is being read at. Every
 * quantity below is already scaled by the ratio of the two.
 */
written_for: number, servings: number, yields: QuantityView | null, components: Array<ComponentView>, steps: Array<StepView>, };
