// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How an ingredient reference renders inside an instruction step. The app
 * applies the rule and sends the pieces to show; this tag travels with them
 * so the UI can style a first mention differently from a later one.
 */
export type RefDisplayTag = "full" | "name_only" | "quantity_only";
