// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuantityView } from "./QuantityView";
import type { RefDisplayTag } from "./RefDisplayTag";

/**
 * A step, resolved. The app has already applied the reference's display
 * rule, so `name` and `quantity` are present exactly when they should be
 * shown; the tag travels along so a first mention can be styled differently
 * from a later one.
 */
export type SegmentView = { "kind": "text", text: string, } | { "kind": "ingredient", usage: string, name: string | null, quantity: QuantityView | null, display: RefDisplayTag, } | { "kind": "missing", usage: string, };
