// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefDisplayTag } from "./RefDisplayTag";

/**
 * A step is a run of segments rather than a string with markers in it, so
 * that editing the prose cannot break a reference (DECISIONS 0022).
 */
export type SegmentInput = { "kind": "text", text: string, } | { "kind": "ingredient", usage: string, display: RefDisplayTag, };
