// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A shop, as the field that creates one sends it: a name and nothing else
 * (DECISIONS 0071).
 */
export type ShopInput = { 
/**
 * Absent on creation. Minted by the frontend in practice, for the reason
 * [`IngredientInput::id`] is: the field that creates a shop has to
 * *select* it the moment it exists, and a command hands back a whole
 * state rather than an id (DECISIONS 0056).
 */
id: string | null, name: string, };
