// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One shop. A name and nothing else, which is the whole of DECISIONS 0071:
 * what a shop is for is answering "can I get this here".
 */
export type ShopView = { id: string, name: string, };
