// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CartView } from "./CartView";
import type { FocusView } from "./FocusView";
import type { IngredientView } from "./IngredientView";
import type { ListEntryView } from "./ListEntryView";
import type { PersonView } from "./PersonView";
import type { ProblemView } from "./ProblemView";
import type { RecipeSummaryView } from "./RecipeSummaryView";
import type { UserView } from "./UserView";

/**
 * Everything on screen, after the last thing that happened.
 */
export type StateView = { 
/**
 * Counts state pushes, so a frontend can tell a new state from a
 * re-render without comparing the whole tree. Resets when the app is
 * reopened; it orders nothing across devices.
 */
revision: number, 
/**
 * Who this device says it is — the name attribution will use.
 */
me: UserView, 
/**
 * Everyone in the family and the devices they carry, in document order.
 * Sorting is the screen's business, like every other list here.
 */
people: Array<PersonView>, cart: CartView, list: Array<ListEntryView>, recipes: Array<RecipeSummaryView>, ingredients: Array<IngredientView>, 
/**
 * The open recipe, if any. Device-local, never synced.
 */
focus: FocusView | null, 
/**
 * What could not be made sense of, usually because another device
 * deleted something this one still refers to. Reported, never fatal
 * (DECISIONS 0022).
 */
problems: Array<ProblemView>, };
