// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SegmentInput } from "./SegmentInput";

export type StepInput = { segments: Array<SegmentInput>, };
