// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SegmentView } from "./SegmentView";

export type StepView = { segments: Array<SegmentView>, };
