// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What it happened to. The id inside the domain's `Subject` is deliberately
 * dropped: the whole point of the log is that the thing may be gone, so the
 * frontend has the label it was called at the time and nothing to look up.
 */
export type SubjectTag = "recipe" | "ingredient" | "list_entry";
