// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuantityInput } from "./QuantityInput";

export type SubRecipeAmountInput = { "kind": "factor", factor: string, } | { "kind": "of_yield", quantity: QuantityInput, };
