// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuantityView } from "./QuantityView";

export type SubRecipeAmountView = { "kind": "factor", factor: string, } | { "kind": "of_yield", quantity: QuantityView, };
