// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncCursor } from "./SyncCursor";

/**
 * The cursor, plus what this one connection has seen.
 */
export type SyncStatus = { 
/**
 * The part worth persisting, and the part to hand back to
 * [`SyncSession::open`] next time.
 */
cursor: SyncCursor, 
/**
 * Frames applied on this connection, replay and live alike. A long
 * replay is the signal to volunteer a [`SyncSession::snapshot`], since
 * compaction is device-driven — the relay cannot merge what it cannot
 * read (0042).
 */
replayed: number, 
/**
 * Frames the family key refused to open. Nonzero is either corruption or
 * company: someone holding the family id, which the relay stores in the
 * clear, but not the phrase.
 */
dropped: number, 
/**
 * The relay served a log that does not hold what the cursor claimed —
 * restored from a backup, or reset. The host reads this to know that its
 * shadow is void and that it owes the family a push even if nothing
 * changed locally (DECISIONS 0054); [`SyncSession::push`] acts on it by
 * itself, so nothing has to be recomputed from it.
 */
reset: boolean, };
