// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a device remembers between connections: which log it was reading, and
 * how far into it (DECISIONS 0042). Zeros on a device that has never synced,
 * which is also what [`Default`] gives.
 */
export type SyncCursor = { 
/**
 * The relay's log identity. A different one means the log this cursor
 * pointed into is gone — restored from a backup, or reset — and the
 * session replays from the beginning rather than from `since`.
 *
 * **Text across the boundary, and only there** (DECISIONS 0046). The
 * relay mints it from 64 bits of the OS's randomness, so almost every
 * epoch there is falls outside what a JavaScript number holds exactly,
 * and `serde_wasm_bindgen` is right to refuse it rather than round it.
 * The host stores this value and hands it back; it never does arithmetic
 * on it. Same answer `store` gives an exact rational, for the same
 * reason (DECISIONS 0029).
 */
epoch: string, 
/**
 * The last sequence number applied. A plain number: the relay hands
 * these out one per frame from 1, so reaching the point where a double
 * stops being exact would take more frames than a family will ever
 * produce.
 */
since: number, };
