// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StateView } from "./StateView";

/**
 * One server message, after the replica has been brought up to date with it.
 *
 * Tagged the way commands are, because the frontend switches on it: the tag
 * is `event`, the variants are `snake_case`.
 */
export type SyncEvent = { "event": "connected" } | { "event": "merged", state: StateView, } | { "event": "caught_up" } | { "event": "acked", seq: number, } | { "event": "refused", reason: string, } | { "event": "dropped", seq: number, };
