// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a device remembers between connections: which log it was reading, and
 * how far into it (DECISIONS 0042). Zeros on a device that has never synced,
 * which is also what [`Default`] gives.
 */
export type SyncCursor = { 
/**
 * The relay's log identity. A different one means the log this cursor
 * pointed into is gone — restored from a backup, or reset — and the
 * session replays from the beginning rather than from `since`.
 */
epoch: number, 
/**
 * The last sequence number applied.
 */
since: number, };
