// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A unit, as the frontend names it. The UI owns the *label* ("c. à s.") —
 * this is the identity underneath it, and it never changes with the
 * language (see the crate docs on where French lives).
 */
export type UnitTag = "mg" | "g" | "kg" | "oz" | "lb" | "ml" | "cl" | "dl" | "l" | "tsp_fr" | "tbsp_fr" | "cup_metric" | "tsp_us" | "tbsp_us" | "cup_us" | "floz_us" | "piece" | "pinch" | "to_taste";
